# Generated by Django 3.1 on 2020-08-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('willto_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='score',
            field=models.IntegerField(choices=[(1, 'Low Impact'), (2, 'Slightly Higher Low Impact'), (3, 'Low High Impact'), (4, 'Slightly Higher Low High Impact'), (5, 'Moderate Impact'), (6, 'Slightly Higher Moderate Impact'), (7, 'Moderate High Impact'), (8, 'Slightly Higher Moderate High Impact'), (9, 'High Moderate Impact'), (10, 'High Impact')]),
        ),
    ]
