# Generated by Django 3.1 on 2020-08-15 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('willto_app', '0002_auto_20200814_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='willto_app.user'),
            preserve_default=False,
        ),
    ]
