# Generated by Django 3.1 on 2020-08-15 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('willto_app', '0003_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(default='no_user', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='willto_app.user'),
        ),
    ]
