# Generated by Django 3.1 on 2020-08-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('willto_app', '0007_auto_20200821_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
