# Generated by Django 3.1 on 2020-08-31 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('willto_app', '0008_task_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='score',
        ),
    ]
